{
  "uid" : "3cd0dbe5cdad533b",
  "name" : "Login under created user",
  "fullName" : "tests.test_users.TestUsers#test_login_user",
  "historyId" : "6035d0badd178081d833aaaec62418fb",
  "time" : {
    "start" : 1742205688434,
    "stop" : 1742205688434,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}",
  "statusTrace" : "self = <test_users.TestUsers object at 0x7fdb26105ed0>\n\n    @pytest.fixture(autouse=True)\n    def cleanup_users(self):\n        \"\"\"Очищаем список юзеров перед каждым тестом\"\"\"\n>       self.api_users.delete_all_users()\n\ntests/test_users.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices/users/api_users.py:96: in delete_all_users\n    feature = self.get_all_users()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.users.api_users.UsersAPI object at 0x7fdb258c4fd0>\n\n    @allure.step(\"Get all users\")\n    def get_all_users(self):\n        response = requests.get(\n            url=self.endpoints.get_users,\n            headers=self.headers.basic,\n            params={\"limit\": 20},\n        )\n>       assert response.status_code == 200, response.json()\nE       AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n\nservices/users/api_users.py:49: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1742205682193,
      "stop" : 1742205682195,
      "duration" : 2
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_xunit_setup_method_fixture_TestUsers",
    "time" : {
      "start" : 1742205688435,
      "stop" : 1742205688435,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "cleanup_users",
    "time" : {
      "start" : 1742205688435,
      "stop" : 1742205689211,
      "duration" : 776
    },
    "status" : "failed",
    "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/API_Auto/API_Auto/tests/test_users.py\", line 13, in cleanup_users\n    self.api_users.delete_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 96, in delete_all_users\n    feature = self.get_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
    "steps" : [ {
      "name" : "Delete all users",
      "time" : {
        "start" : 1742205688435,
        "stop" : 1742205689211,
        "duration" : 776
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 96, in delete_all_users\n    feature = self.get_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
      "steps" : [ {
        "name" : "Get all users",
        "time" : {
          "start" : 1742205688435,
          "stop" : 1742205689211,
          "duration" : 776
        },
        "status" : "failed",
        "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
        "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : true,
        "hasContent" : true
      } ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 1,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 2,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "_xunit_setup_method_fixture_TestUsers::0",
    "time" : {
      "start" : 1742205689218,
      "stop" : 1742205689218,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Users"
  }, {
    "name" : "epic",
    "value" : "Administration"
  }, {
    "name" : "tag",
    "value" : "regress"
  }, {
    "name" : "tag",
    "value" : "smoke"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_users"
  }, {
    "name" : "subSuite",
    "value" : "TestUsers"
  }, {
    "name" : "host",
    "value" : "fv-az1280-703"
  }, {
    "name" : "thread",
    "value" : "2565-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_users"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 4,
        "unknown" : 0,
        "total" : 6
      },
      "items" : [ {
        "uid" : "40ed6ee34d4362b",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/26/#testresult/40ed6ee34d4362b",
        "status" : "failed",
        "statusDetails" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}",
        "time" : {
          "start" : 1742205453118,
          "stop" : 1742205453118,
          "duration" : 0
        }
      }, {
        "uid" : "31df3c83d928344c",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/24/#testresult/31df3c83d928344c",
        "status" : "passed",
        "time" : {
          "start" : 1741967979450,
          "stop" : 1741967982697,
          "duration" : 3247
        }
      }, {
        "uid" : "b15d51eb844797ed",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/23/#testresult/b15d51eb844797ed",
        "status" : "passed",
        "time" : {
          "start" : 1741966139488,
          "stop" : 1741966143047,
          "duration" : 3559
        }
      }, {
        "uid" : "efcb73d3d01cdfd8",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/22/#testresult/efcb73d3d01cdfd8",
        "status" : "passed",
        "time" : {
          "start" : 1741964647086,
          "stop" : 1741964650305,
          "duration" : 3219
        }
      }, {
        "uid" : "9d9f27060385c091",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/21/#testresult/9d9f27060385c091",
        "status" : "passed",
        "time" : {
          "start" : 1741964091352,
          "stop" : 1741964094749,
          "duration" : 3397
        }
      } ]
    },
    "tags" : [ "regress", "smoke" ]
  },
  "source" : "3cd0dbe5cdad533b.json",
  "parameterValues" : [ ]
}