{
  "uid" : "f354849b43f35ad9",
  "name" : "Delete created user",
  "fullName" : "tests.test_users.TestUsers#test_delete_user",
  "historyId" : "6f3e778a3f95b7678941ec2b2bb01b94",
  "time" : {
    "start" : 1742205686768,
    "stop" : 1742205686768,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}",
  "statusTrace" : "self = <test_users.TestUsers object at 0x7fdb26105120>\n\n    @pytest.fixture(autouse=True)\n    def cleanup_users(self):\n        \"\"\"Очищаем список юзеров перед каждым тестом\"\"\"\n>       self.api_users.delete_all_users()\n\ntests/test_users.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices/users/api_users.py:96: in delete_all_users\n    feature = self.get_all_users()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.users.api_users.UsersAPI object at 0x7fdb25867430>\n\n    @allure.step(\"Get all users\")\n    def get_all_users(self):\n        response = requests.get(\n            url=self.endpoints.get_users,\n            headers=self.headers.basic,\n            params={\"limit\": 20},\n        )\n>       assert response.status_code == 200, response.json()\nE       AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n\nservices/users/api_users.py:49: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_xunit_setup_method_fixture_TestUsers",
    "time" : {
      "start" : 1742205686768,
      "stop" : 1742205686768,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1742205682193,
      "stop" : 1742205682195,
      "duration" : 2
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "cleanup_users",
    "time" : {
      "start" : 1742205686768,
      "stop" : 1742205687432,
      "duration" : 664
    },
    "status" : "failed",
    "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/API_Auto/API_Auto/tests/test_users.py\", line 13, in cleanup_users\n    self.api_users.delete_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 96, in delete_all_users\n    feature = self.get_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
    "steps" : [ {
      "name" : "Delete all users",
      "time" : {
        "start" : 1742205686768,
        "stop" : 1742205687431,
        "duration" : 663
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 96, in delete_all_users\n    feature = self.get_all_users()\n  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
      "steps" : [ {
        "name" : "Get all users",
        "time" : {
          "start" : 1742205686768,
          "stop" : 1742205687431,
          "duration" : 663
        },
        "status" : "failed",
        "statusMessage" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}\n",
        "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/API_Auto/API_Auto/services/users/api_users.py\", line 49, in get_all_users\n    assert response.status_code == 200, response.json()\n",
        "steps" : [ ],
        "attachments" : [ ],
        "parameters" : [ ],
        "stepsCount" : 0,
        "attachmentsCount" : 0,
        "shouldDisplayMessage" : true,
        "hasContent" : true
      } ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 1,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 2,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "_xunit_setup_method_fixture_TestUsers::0",
    "time" : {
      "start" : 1742205687438,
      "stop" : 1742205687438,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Users"
  }, {
    "name" : "epic",
    "value" : "Administration"
  }, {
    "name" : "tag",
    "value" : "regress"
  }, {
    "name" : "tag",
    "value" : "smoke"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_users"
  }, {
    "name" : "subSuite",
    "value" : "TestUsers"
  }, {
    "name" : "host",
    "value" : "fv-az1280-703"
  }, {
    "name" : "thread",
    "value" : "2565-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_users"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 4,
        "unknown" : 0,
        "total" : 6
      },
      "items" : [ {
        "uid" : "e25a3d4c287ae398",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/26/#testresult/e25a3d4c287ae398",
        "status" : "failed",
        "statusDetails" : "AssertionError: {'code': 401, 'message': 'security requirements failed: authentication failed, please set correct \"Bearer\" header'}",
        "time" : {
          "start" : 1742205451173,
          "stop" : 1742205451173,
          "duration" : 0
        }
      }, {
        "uid" : "c067ebeee6bec3cc",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/24/#testresult/c067ebeee6bec3cc",
        "status" : "passed",
        "time" : {
          "start" : 1741967971815,
          "stop" : 1741967974072,
          "duration" : 2257
        }
      }, {
        "uid" : "1e754c9a500cf8",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/23/#testresult/1e754c9a500cf8",
        "status" : "passed",
        "time" : {
          "start" : 1741966131865,
          "stop" : 1741966134163,
          "duration" : 2298
        }
      }, {
        "uid" : "d922dacf97db86ea",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/22/#testresult/d922dacf97db86ea",
        "status" : "passed",
        "time" : {
          "start" : 1741964638845,
          "stop" : 1741964641263,
          "duration" : 2418
        }
      }, {
        "uid" : "5303352eec5d6a86",
        "reportUrl" : "https://AntonAlisevich.github.io/API_Auto/21/#testresult/5303352eec5d6a86",
        "status" : "passed",
        "time" : {
          "start" : 1741964082959,
          "stop" : 1741964085390,
          "duration" : 2431
        }
      } ]
    },
    "tags" : [ "regress", "smoke" ]
  },
  "source" : "f354849b43f35ad9.json",
  "parameterValues" : [ ]
}